### ISSUE TITLE
jsonファイルにスラッシュのコメントアウトは使用できない

### ISSUE THREAD

**Issue by yoshi1125hisa** [Genbuchan/dotfiles#3]
`dotfiles/Code/User/settings.json`

jsonに `//` は使用できないので、以下
https://www.nxworld.net/tips/use-comment-in-json.html
などの方法でコメントアウトする方法がよいと思われます。

**Comment by Genbuchan** [comment]
対応しました！ありがとうございます。

なお、VSCodeで自動生成されたコメントなので、削除するか迷いましたが、公式の仕様に準拠してコメント削除を行いました。
